### ISSUE TITLE
Tinkers' construct; 'half-implemented' arrowheads cause crashes

### ISSUE THREAD

**Issue by outofwords** [RTRGitHub/RTRRedux#102]
You can use the smeltery to make arrowheads out of most metals, most of which work fine on swords. But for arrows they don't seem to be implemented fully. I just made myself a silver arrowhead, and upon putting it into the tool forge minecraft instantly crashes. I assume it will happen with all the arrowheads which don't have the full tooltip in NEI, I tried a silver one because it did not have the -4% accuracy tooltip. (tried twice, crashed twice)
Upon logging back in the arrowhead was on the floor, so no permanent damage.

console log:
[24/12/2014 20:01:49 PM] Console Cleared
[24/12/2014 20:02:02 PM] [20:02:02] [Client thread/ERROR] [FML]: Exception caught during firing event tconstruct.library.event.ToolCraftEvent$NormalTool@c546a79:
[24/12/2014 20:02:02 PM] java.lang.NullPointerException
[24/12/2014 20:02:02 PM]    at tconstruct.weaponry.WeaponryHandler.onAmmoCrafted(WeaponryHandler.java:78) ~[WeaponryHandler.class:?]
[24/12/2014 20:02:02 PM]    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1050_WeaponryHandler_onAmmoCrafted_NormalTool.invoke(.dynamic) ~[?:?]
[24/12/2014 20:02:02 PM]    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[24/12/2014 20:02:02 PM]    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
[24/12/2014 20:02:02 PM]    at tconstruct.library.crafting.ToolBuilder.buildTool(ToolBuilder.java:321) [ToolBuilder.class:?]
[24/12/2014 20:02:02 PM]    at tconstruct.tools.logic.ToolForgeLogic.buildTool(ToolForgeLogic.java:56) [ToolForgeLogic.class:?]
[24/12/2014 20:02:02 PM]    at tconstruct.tools.logic.ToolStationLogic.func_70296_d(ToolStationLogic.java:63) [ToolStationLogic.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83) [aay.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78) [aay.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.inventory.Container.func_75144_a(SourceFile:222) [zs.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419) [bje.class:?]
[24/12/2014 20:02:02 PM]    at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503) [GuiContainerManager.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638) [bex.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java) [bex.class:?]
[24/12/2014 20:02:02 PM]    at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java) [DefaultSlotClickHandler.class:?]
[24/12/2014 20:02:02 PM]    at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17) [DefaultSlotClickHandler.class:?]
[24/12/2014 20:02:02 PM]    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452) [GuiContainerManager.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java) [bex.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607) [bex.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306) [bdw.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java) [bex.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) [bdw.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629) [bao.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) [bao.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[24/12/2014 20:02:02 PM]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_45]
[24/12/2014 20:02:02 PM]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
[24/12/2014 20:02:02 PM]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
[24/12/2014 20:02:02 PM]    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
[24/12/2014 20:02:02 PM]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[24/12/2014 20:02:02 PM]    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[24/12/2014 20:02:02 PM] [Client thread/ERROR] [FML]: Index: 2 Listeners:
[24/12/2014 20:02:02 PM] [Client thread/ERROR] [FML]: 0: NORMAL
[24/12/2014 20:02:02 PM] [Client thread/ERROR] [FML]: 1: ASM: tconstruct.tools.TinkerToolEvents@68711614 craftTool(Ltconstruct/library/event/ToolCraftEvent$NormalTool;)V
[24/12/2014 20:02:02 PM] [Client thread/ERROR] [FML]: 2: ASM: tconstruct.weaponry.WeaponryHandler@596c290c onAmmoCrafted(Ltconstruct/library/event/ToolCraftEvent$NormalTool;)V
[24/12/2014 20:02:02 PM] [Client thread/ERROR] [FML]: 3: ASM: tconstruct.weaponry.WeaponryHandler@596c290c onProjectileWeaponCrafted(Ltconstruct/library/event/ToolCraftEvent$NormalTool;)V
[24/12/2014 20:02:04 PM] Copied Log to clipboard

**Comment by RTRGitHub** [comment]
This is TInkers Tool Tips being derpy as it isn't updated yet. dont hold shifft while putting them in/hovering over the items. see what happens.

kenny

**Comment by RTRGitHub** [comment]
Expanding this, I'd recommend you remove Tinkers tool tips client side, see if that helps, as I believe this is caused by that.
