### ISSUE TITLE
Upon attempting to open crystal chests Minecraft crashes.

### ISSUE THREAD

**Issue by bradroeger** [RTRGitHub/RTRRedux#111]
As the subject says myself and Sam attempted to open Niels Crystal chests and crashed immideatly.

**Comment by Abouttabs** [comment]
We'll need catalogs to be able to do anything with it..

**Comment by bradroeger** [comment]
[02/1/2015 10:31:44 AM] Exception in thread "NEI Subset Item Allocation" [10:31:44] [NEI Subset Item Allocation/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[02/1/2015 10:31:44 AM] [10:31:44] [NEI Subset Item Allocation/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.bdew.neiaddons.utils.ModItemFilter.matches(ModItemFilter.java:30)
[02/1/2015 10:31:44 AM] [10:31:44] [NEI Subset Item Allocation/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.bdew.neiaddons.forestry.ForestryOtherFilter.matches(ForestryOtherFilter.java:23)
[02/1/2015 10:31:44 AM] [10:31:44] [NEI Subset Item Allocation/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at codechicken.nei.SubsetWidget$UpdateStateTask.execute(SubsetWidget.java:533)
[02/1/2015 10:31:44 AM] [10:31:44] [NEI Subset Item Allocation/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24)
[02/1/2015 10:31:45 AM] [Client thread/INFO] [FML]: Applying holder lookups
[02/1/2015 10:31:45 AM] [Client thread/INFO] [FML]: Holder lookups applied
[02/1/2015 10:31:48 AM] [10:31:48] [Client thread/FATAL]: Reported exception thrown!
[02/1/2015 10:31:48 AM] net.minecraft.util.ReportedException: Rendering item
[02/1/2015 10:31:48 AM]     at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1092) ~[blt.class:?]
[02/1/2015 10:31:48 AM]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990) ~[bao.class:?]
[02/1/2015 10:31:48 AM]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[02/1/2015 10:31:48 AM]     at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[02/1/2015 10:31:48 AM]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_04]
[02/1/2015 10:31:48 AM]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_04]
[02/1/2015 10:31:48 AM]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_04]
[02/1/2015 10:31:48 AM]     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_04]
[02/1/2015 10:31:48 AM]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[02/1/2015 10:31:48 AM]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[02/1/2015 10:31:48 AM] Caused by: java.lang.NullPointerException
[02/1/2015 10:31:48 AM]     at tconstruct.library.tools.ToolCore.getDefaultColor(ToolCore.java:677) ~[ToolCore.class:?]
[02/1/2015 10:31:48 AM]     at tconstruct.library.tools.ToolCore.getCorrectColor(ToolCore.java:672) ~[ToolCore.class:?]
[02/1/2015 10:31:48 AM]     at tconstruct.library.tools.ToolCore.func_82790_a(ToolCore.java:651) ~[ToolCore.class:?]
[02/1/2015 10:31:48 AM]     at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:485) ~[bny.class:?]
[02/1/2015 10:31:48 AM]     at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565) ~[bny.class:?]
[02/1/2015 10:31:48 AM]     at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488) ~[GuiContainerManager.class:?]
[02/1/2015 10:31:48 AM]     at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270) ~[bex.class:?]
[02/1/2015 10:31:48 AM]     at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99) ~[bex.class:?]
[02/1/2015 10:31:48 AM]     at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) ~[blt.class:?]
[02/1/2015 10:31:48 AM]     ... 9 more
[02/1/2015 10:31:48 AM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[02/1/2015 10:31:48 AM] // Don't do that.
[02/1/2015 10:31:48 AM] 
[02/1/2015 10:31:48 AM] Time: 1/2/15 10:31 AM
[02/1/2015 10:31:48 AM] Description: Rendering item
[02/1/2015 10:31:48 AM] 
[02/1/2015 10:31:48 AM] java.lang.NullPointerException: Rendering item
[02/1/2015 10:31:48 AM]     at tconstruct.library.tools.ToolCore.getDefaultColor(ToolCore.java:677)
[02/1/2015 10:31:48 AM]     at tconstruct.library.tools.ToolCore.getCorrectColor(ToolCore.java:672)
[02/1/2015 10:31:48 AM]     at tconstruct.library.tools.ToolCore.func_82790_a(ToolCore.java:651)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:485)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
[02/1/2015 10:31:48 AM]     at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.main.Main.main(SourceFile:148)
[02/1/2015 10:31:48 AM]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02/1/2015 10:31:48 AM]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02/1/2015 10:31:48 AM]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02/1/2015 10:31:48 AM]     at java.lang.reflect.Method.invoke(Unknown Source)
[02/1/2015 10:31:48 AM]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[02/1/2015 10:31:48 AM]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02/1/2015 10:31:48 AM] 
[02/1/2015 10:31:48 AM] 
[02/1/2015 10:31:48 AM] A detailed walkthrough of the error, its code path and all known details is as follows:
[02/1/2015 10:31:48 AM] ---------------------------------------------------------------------------------------
[02/1/2015 10:31:48 AM] 
[02/1/2015 10:31:48 AM] -- Head --
[02/1/2015 10:31:48 AM] Stacktrace:
[02/1/2015 10:31:48 AM]     at tconstruct.library.tools.ToolCore.getDefaultColor(ToolCore.java:677)
[02/1/2015 10:31:48 AM]     at tconstruct.library.tools.ToolCore.getCorrectColor(ToolCore.java:672)
[02/1/2015 10:31:48 AM]     at tconstruct.library.tools.ToolCore.func_82790_a(ToolCore.java:651)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:485)
[02/1/2015 10:31:48 AM] 
[02/1/2015 10:31:48 AM] -- Item being rendered --
[02/1/2015 10:31:48 AM] Details:
[02/1/2015 10:31:48 AM]     Item Type: tconstruct.items.tools.Cleaver@1f569bb7
[02/1/2015 10:31:48 AM]     Item Aux: 1
[02/1/2015 10:31:48 AM]     Item NBT: {RepairCost:2,InfiTool:{Unbreaking:2,Damage:3,Extra:10,MiningSpeed2:1400,HarvestLevel:2,Head:139,BaseDurability:5414,RenderExtra:10,Accessory:10,Modifiers:3,RenderHead:139,Handle:10,HarvestLevel2:4,Shoddy:0.0f,Attack:10,RenderHandle:10,MiningSpeed:1400,ModDurability:0.0f,Broken:0b,BonusDurability:0,TotalDurability:5414,RenderAccessory:10},display:{Name:"Glowing Cleaver"}}
[02/1/2015 10:31:48 AM]     Item Foil: false
[02/1/2015 10:31:48 AM] Stacktrace:
[02/1/2015 10:31:48 AM]     at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
[02/1/2015 10:31:48 AM]     at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
[02/1/2015 10:31:48 AM] 
[02/1/2015 10:31:48 AM] -- Screen render details --
[02/1/2015 10:31:48 AM] Details:
[02/1/2015 10:31:48 AM]     Screen name: cpw.mods.ironchest.client.GUIChest
[02/1/2015 10:31:48 AM]     Mouse location: Scaled: (213, 119). Absolute: (427, 240)
[02/1/2015 10:31:48 AM]     Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
[02/1/2015 10:31:48 AM] 
[02/1/2015 10:31:48 AM] -- Affected level --
[02/1/2015 10:31:48 AM] Details:
[02/1/2015 10:31:48 AM]     Level name: MpServer
[02/1/2015 10:31:48 AM]     All players: 1 total; [EntityClientPlayerMP['**MINECRAFTUSERNAME**'/632976, l='MpServer', x=-1426.45, y=75.62, z=393.86]]
[02/1/2015 10:31:48 AM]     Chunk stats: MultiplayerChunkCache: 169, 169
[02/1/2015 10:31:48 AM]     Level seed: 0
[02/1/2015 10:31:48 AM]     Level generator: ID 00 - default, ver 1. Features enabled: false
[02/1/2015 10:31:48 AM]     Level generator options: 
[02/1/2015 10:31:48 AM]     Level spawn location: World: (-30,69,4), Chunk: (at 2,4,4 in -2,0; contains blocks -32,0,0 to -17,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
[02/1/2015 10:31:48 AM]     Level time: 30338276 game time, 33337007 day time
[02/1/2015 10:31:48 AM]     Level dimension: 0
[02/1/2015 10:31:48 AM]     Level storage version: 0x00000 - Unknown?
[02/1/2015 10:31:48 AM]     Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
[02/1/2015 10:31:48 AM]     Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
[02/1/2015 10:31:48 AM]     Forced entities: 28 total; [EntityWitch['Witch'/638478, l='MpServer', x=-1442.91, y=92.00, z=379.34], EntityCreeper['Creeper'/639672, l='MpServer', x=-1460.50, y=71.00, z=371.50], EntityZombie['Zombie'/638477, l='MpServer', x=-1452.50, y=83.00, z=377.50], EntityTrail['unknown'/558, l='MpServer', x=-1426.45, y=75.62, z=393.86], EntityHat['unknown'/9358, l='MpServer', x=-1475.50, y=63.00, z=433.50], EntitySkeleton['Skeleton'/639671, l='MpServer', x=-1459.50, y=71.00, z=371.50], EntityHat['unknown'/9357, l='MpServer', x=-1476.50, y=108.00, z=407.50], EntityClientPlayerMP['**MINECRAFTUSERNAME**'/632976, l='MpServer', x=-1426.45, y=75.62, z=393.86], EntitySilverfish['Silverfish'/8411, l='MpServer', x=-18.55, y=-29.91, z=-18.94], EntityItemFrame['entity.ItemFrame.name'/311, l='MpServer', x=-1430.94, y=75.50, z=394.50], EntityZombie['Zombie'/633209, l='MpServer', x=-1385.00, y=11.10, z=452.70], EntitySilverfish['Silverfish'/8180, l='MpServer', x=-37.42, y=-34.18, z=8.93], EntityHat['unknown'/8306, l='MpServer', x=-1385.00, y=11.10, z=452.70], EntitySkeleton['Skeleton'/639890, l='MpServer', x=-1459.50, y=89.00, z=367.50], EntityZombie['Zombie'/639891, l='MpServer', x=-1462.50, y=156.00, z=358.50], EntitySkeleton['Skeleton'/639889, l='MpServer', x=-1459.50, y=70.00, z=439.50], EntitySilverfish['Silverfish'/2960, l='MpServer', x=-32.60, y=-27.62, z=-22.77], EntityZombie['Zombie'/639604, l='MpServer', x=-1422.44, y=35.00, z=347.94], EntityHat['unknown'/350, l='MpServer', x=-1426.45, y=75.62, z=393.86], EntitySilverfish['Silverfish'/7353, l='MpServer', x=-23.50, y=-23.33, z=-4.96], EntitySquid['Squid'/638804, l='MpServer', x=-1455.92, y=62.19, z=385.22], EntitySquid['Squid'/638805, l='MpServer', x=-1461.72, y=62.06, z=401.72], EntityZombie['Zombie'/640004, l='MpServer', x=-1476.50, y=108.00, z=407.50], EntitySheep['Sheep'/640005, l='MpServer', x=-1482.53, y=145.00, z=383.47], EntitySkeleton['Skeleton'/640006, l='MpServer', x=-1479.50, y=100.00, z=346.50], EntityZombie['Zombie'/640002, l='MpServer', x=-1475.50, y=63.00, z=433.50], EntityCreeper['Creeper'/640003, l='MpServer', x=-1473.09, y=64.00, z=428.50], EntityCreeper['Creeper'/639825, l='MpServer', x=-1469.34, y=64.00, z=430.31]]
[02/1/2015 10:31:48 AM]     Retry entities: 0 total; []
[02/1/2015 10:31:48 AM]     Server brand: cauldron,craftbukkit,mcpc,fml,forge
[02/1/2015 10:31:48 AM]     Server type: Non-integrated multiplayer server
[02/1/2015 10:31:48 AM] Stacktrace:
[02/1/2015 10:31:48 AM]     at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
[02/1/2015 10:31:48 AM]     at net.minecraft.client.main.Main.main(SourceFile:148)
[02/1/2015 10:31:48 AM]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02/1/2015 10:31:48 AM]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02/1/2015 10:31:48 AM]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02/1/2015 10:31:48 AM]     at java.lang.reflect.Method.invoke(Unknown Source)
[02/1/2015 10:31:48 AM]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[02/1/2015 10:31:48 AM]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02/1/2015 10:31:48 AM] 
[02/1/2015 10:31:48 AM] -- System Details --
[02/1/2015 10:31:48 AM] Details:
[02/1/2015 10:31:48 AM]     Minecraft Version: 1.7.10
[02/1/2015 10:31:48 AM]     Operating System: Windows 7 (amd64) version 6.1
[02/1/2015 10:31:48 AM]     Java Version: 1.7.0_04, Oracle Corporation
[02/1/2015 10:31:48 AM]     Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[02/1/2015 10:31:48 AM]     Memory: 2579948072 bytes (2460 MB) / 4027314176 bytes (3840 MB) up to 4260102144 bytes (4062 MB)
[02/1/2015 10:31:48 AM]     JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx4096M -XX:PermSize=256M
[02/1/2015 10:31:48 AM]     AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[02/1/2015 10:31:48 AM]     IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
[02/1/2015 10:31:48 AM]     FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 152 mods loaded, 152 mods active
[02/1/2015 10:31:48 AM]     mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     FML{7.10.85.1236} [Forge Mod Loader](forge-1.7.10-10.13.2.1236-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     Forge{10.13.2.1236} [Minecraft Forge](forge-1.7.10-10.13.2.1236-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     appliedenergistics2-core{rv2-beta-6} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     NotEnoughItems{1.0.3.78} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.78-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     OpenComputers|Core{1.0.0} [OpenComputers (Core)](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     debug{1.0} [debug](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     EnderTech{1.7.10-0.3.0.358} [EnderTech](EnderTech-1.7.10-0.3.0.358.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     iChunUtil{4.1.2} [iChunUtil](iChunUtil-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     MekanismTools{7.1.1} [MekanismTools](MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     MrTJPCoreMod{1.0} [MrTJPCoreMod](MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC6} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-263.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     RandomThings{2.1.4} [Random Things](RandomThings-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[02/1/2015 10:31:48 AM]     AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
[02/1/2015 10:31:48 AM]     Resource Packs: [Sphax-x64-5.zip]
[02/1/2015 10:31:48 AM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**\Instances\RightToRebel\crash-reports\crash-2015-01-02_10.31.48-client.txt
[02/1/2015 10:31:48 AM] process has not exited
[02/1/2015 10:31:48 AM] java.lang.ProcessImpl.exitValue(Unknown Source)
[02/1/2015 10:31:48 AM] com.atlauncher.data.Instance$2.run(Instance.java:1185)
[02/1/2015 10:31:48 AM] Checking for updated files!
[02/1/2015 10:31:48 AM] Updates found!
[02/1/2015 10:31:48 AM] Checking for updated files!
[02/1/2015 10:31:48 AM] Updates found!
[02/1/2015 10:31:48 AM] Downloading Launcher File packs.json
[02/1/2015 10:31:48 AM] Finished downloading updated files!
[02/1/2015 10:31:48 AM] Loading Language: English

**Comment by bradroeger** [comment]
Upon investigation and looking at the logs it looks like its something in one of Niels chests that causes the problem. Looks like something he made out of glowstone.

**Comment by Abouttabs** [comment]
fixed by readding extraTIC
