### ISSUE TITLE
Cannot Join

### ISSUE THREAD

**Issue by adrlmrtz** [RTRGitHub/RTRRedux#588]
Has the server changed modpacks or been updated? I tried with 1.5 and now with 1.6 and I cannot connect. In the screen I get a looong list of mods (e.g. FMLMod:SimpleDimensions{1.3}, FMLMod:pressure{1.3.1.22} etc...). I am using the curse launcher, is there something I should be doing to connect? 
EDIT: I Installed Bevo's Superstitions and all that, but when I click play in the ATLauncher, it just loads a bar then nothing happens.

**Comment by selfup** [comment]
If you are using an NVIDIA GPU you will need this NVIDIA Driver Hotfix: https://nvidia.custhelp.com/app/answers/detail/a_id/4378/~/geforce-hot-fix-driver-version-378.57

**Comment by adrlmrtz** [comment]
I will try this now and edit with an update. Thank you! 
UPDATE: Installed the NVIDIA file and it opened, registered, and added a bunch of my games. Re-set the ATLauncher and tried opening Bevo's supersitions again (3.0.0 and 3.1) and same thing happens (opens loading bar then nothing happens). :( 

ERROR MESSAGE: [12/2/2017 18:58:09 PM] Exception in thread "main" [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.UnsupportedClassVersionError: appeng/coremod/AppEngCore : Unsupported major.minor version 52.0
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.forName0(Native Method)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.forName(Unknown Source)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:552)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:423)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:253)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[12/2/2017 18:58:09 PM] [18:58:09] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by adrlmrtz** [comment]
Also is there any documented change on why the server switched modpacks? What happened to all our stuff/base/progress from before (Infinity lite)? Thanks for the help.

**Comment by selfup** [comment]
Yea I was surprised by this as well. I would ask @Solidflip @dragonaslin

Glad it all worked out 😄

**Comment by selfup** [comment]
Yea our server runs 3.0.0 so you will have to stick to that.

Best advise is to quite and restart the launcher and hope that helps.

Otherwise I don't know 😂 

Hopefully @Solidflip can help out here

**Comment by dragonaslin** [comment]
update your java 64 bit

**Comment by adrlmrtz** [comment]
I updated to Java 8 and now it works, thank you! @dragonaslin what happened to all the progress we had made before? I really love this new modpack and will continue to play but do we simply loose everything we worked for before? Anyway we can get a save from our map so we can play if on our own (singleplayer) please?

**Comment by dragonaslin** [comment]
will talk in game and glad you made it on
