### ISSUE TITLE
NEI crashes of some sort, or TF, MFR, or ?

### ISSUE THREAD

**Issue by Work-work** [RTRGitHub/RTRRedux#87]
2 crash reports headers , not sure if its NEI, TF, or MFR

---

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 11/14/14 7:07 PM
Description: Rendering item

java.lang.ClassCastException: twilightforest.entity.TFEntityEggInfo cannot be cast to net.minecraft.entity.EntityList$EntityEggInfo
    at powercrystals.minefactoryreloaded.modhelpers.twilightforest.TwilightForestEggHandler.getEgg(TwilightForestEggHandler.java:28)
    at powercrystals.minefactoryreloaded.item.ItemSafariNet.getEgg(ItemSafariNet.java:174)
    at powercrystals.minefactoryreloaded.item.ItemSafariNet.func_82790_a(ItemSafariNet.java:145)
    at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:485)

---

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 11/14/14 9:29 PM
Description: Rendering item

java.lang.ClassCastException: twilightforest.entity.TFEntityEggInfo cannot be cast to net.minecraft.entity.EntityList$EntityEggInfo
    at powercrystals.minefactoryreloaded.modhelpers.twilightforest.TwilightForestEggHandler.getEgg(TwilightForestEggHandler.java:28)
    at powercrystals.minefactoryreloaded.item.ItemSafariNet.getEgg(ItemSafariNet.java:174)
    at powercrystals.minefactoryreloaded.item.ItemSafariNet.func_82790_a(ItemSafariNet.java:145)

**Comment by Abouttabs** [comment]
I know about this issue, I have thought of temporary measure and will open ticket on mfr's github.  
If you have the issue post the chest coords and I will get it sorted...

**Comment by Volaunis** [comment]
I'm having the same issue, chest with safari nets in it, at 289, 71, -1535 (or 36, depending on how you look at it). Seems to be the ghastling one that borks it.

**Comment by Work-work** [comment]
Yeah, it's the ghastling one for me too.

**Comment by Solidflip** [comment]
Please comment if the chest is still there with the safari net. If not i will close this issue in 2 days.
